-- Generated by Noctalia
local colors = {
	bg = "{{colors.surface.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
	primary = "{{colors.primary.default.hex}}",
	tertiary = "{{colors.tertiary.default.hex}}",
	surface = "{{colors.surface_variant.default.hex}}",
	muted = "{{colors.on_surface_variant.default.hex}}",
	outline = "{{colors.outline.default.hex}}",
	error = "{{colors.error.default.hex}}",
}

vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "noctalia"

local function hi(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal", { fg = colors.fg, bg = colors.bg })
hi("NormalFloat", { fg = colors.fg, bg = colors.surface })
hi("Comment", { fg = colors.outline, italic = true })
hi("Keyword", { fg = colors.primary, bold = true })
hi("Function", { fg = colors.tertiary, bold = true })
hi("String", { fg = colors.muted })
hi("Number", { fg = colors.error })
hi("Boolean", { fg = colors.error })
hi("Type", { fg = colors.primary })
hi("Identifier", { fg = colors.fg })
hi("Statement", { fg = colors.primary, bold = true })
hi("Operator", { fg = colors.tertiary })
hi("PreProc", { fg = colors.tertiary })
hi("Special", { fg = colors.error })
hi("Constant", { fg = colors.error })
hi("LineNr", { fg = colors.outline })
hi("CursorLine", { bg = colors.surface })
hi("CursorLineNr", { fg = colors.primary, bold = true })
hi("Visual", { bg = colors.surface })
hi("Search", { fg = colors.bg, bg = colors.primary })
hi("IncSearch", { fg = colors.bg, bg = colors.tertiary })
hi("StatusLine", { fg = colors.fg, bg = colors.surface })
hi("StatusLineNC", { fg = colors.outline, bg = colors.surface })
hi("Pmenu", { fg = colors.fg, bg = colors.surface })
hi("PmenuSel", { fg = colors.bg, bg = colors.primary })
hi("WinSeparator", { fg = colors.outline })
hi("TabLine", { fg = colors.outline, bg = colors.surface })
hi("TabLineSel", { fg = colors.bg, bg = colors.primary })
hi("TabLineFill", { bg = colors.bg })
hi("DiagnosticError", { fg = colors.error })
hi("DiagnosticWarn", { fg = colors.tertiary })
hi("DiagnosticInfo", { fg = colors.primary })
hi("DiagnosticHint", { fg = colors.muted })
