# Качество
Ctrl+1 set ytdl-format "best[height<=480]"   #menu: Качество > 480p
Ctrl+2 set ytdl-format "best[height<=720]"   #menu: Качество > 720p
Ctrl+3 set ytdl-format "best[height<=1080]"  #menu: Качество > 1080p
Ctrl+4 set ytdl-format "best[height<=1440]"  #menu: Качество > 1440p
F     script-binding quality_menu/video_formats_toggle
Alt+f script-binding quality_menu/audio_formats_toggle

# Навигация
Alt+f script-binding filenavigator          #menu: Открыть > Файловый навигатор
g script-binding playlist-view/open         #menu: Открыть > Галерея плейлиста

# Воспроизведение
Ctrl+r playlist-play-index current          #menu: Воспроизведение > Перезагрузить
a cycle audio                               #menu: Воспроизведение > Аудио дорожка
s cycle sub                                 #menu: Воспроизведение > Субтитры

# Перемотка
LEFT seek -5
RIGHT seek 5
UP seek 60
DOWN seek -60

# Громкость
+ add volume 5
- add volume -5
