## Output
vo=gpu
gpu-api=opengl
audio-channels=stereo

## HWDEC
hwdec=vaapi

## Window
force-window=yes
geometry=50%
border=no
osd-on-seek=msg
osd-duration=7000
osc=no

## Subs
sub-auto=fuzzy
slang=ru,en
sub-font-size=54
sub-border-size=2
sid=no

## Cache
cache=yes
cache-secs=600
cache-pause=yes
demuxer-max-bytes=80MiB
demuxer-max-back-bytes=40MiB
save-position-on-quit=yes
autocreate-playlist=same

## Performance
profile=fast
video-sync=audio
interpolation=no
tscale=box
correct-pts=yes
deband=no
fbo-format=rgba8
framedrop=decoder+vo
hr-seek=yes

## Scale
scale=bilinear
cscale=bilinear
dscale=bilinear
correct-downscaling=no
linear-downscaling=no
sigmoid-upscaling=no

## Keyboard

## Скрипты
load-scripts=no
watch-later-options-remove=sub-pos
osd-font='Noto Sans'
# script=/usr/share/mpv/scripts/autocrop.lua
script=/usr/share/mpv/scripts/autoload.lua
# script=/usr/share/mpv/scripts/skip-logo.lua
script=/usr/share/mpv/scripts/ontop-playback.lua
# script=/usr/share/mpv/scripts/pause-when-minimize.lua
script=/usr/share/mpv/scripts/status-line.lua
# script=/usr/share/mpv/scripts/acompressor.lua
# script=/usr/share/mpv/scripts/ao-null-reload.lua
script=/etc/mpv/scripts/quality-menu.lua
script=/etc/mpv/scripts/quality-menu-osc.lua
# script=/etc/mpv/scripts/thumbfast.lua
# script=/etc/mpv/scripts/modernx.lua
script=/etc/mpv/scripts/mpris.so
# script=~/.config/mpv/scripts/filenavigator.lua
# script=~/.config/mpv/scripts/autosub.lua
# script=~/.config/mpv/scripts/sponsorblock.so
# script=~/.config/mpv/scripts/autosubsync/autosubsync.lua
