# ===========================================
# Основной конфигурационный файл Hyprland
# ===========================================

$config = $HOME/.config/hypr/config
# Импорт модулей
source = $config/startup.conf
source = $config/appearance.conf
source = $config/keybinds.conf
source = $config/input.conf
source = $config/misc.conf

# ===========================================
# Базовые настройки мониторов
# ===========================================
monitor = ,preferred,auto,1

env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,16

# Оптимизация для GPU
env = LIBVA_DRIVER_NAME,i965
env = LIBVA_DRIVERS_PATH,/usr/lib/dri
env = VDPAU_DRIVER,va_gl
env = WLR_NO_HARDWARE_CURSORS,1

# Qt и GTK настройки
env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_LOGGING_RULES,qt.scenegraph.general=false
env = GTK_THEME,tokyonight-dark1
env = QT_QPA_PLATFORMTHEME,qt6ct

# Electron/Chromium оптимизации
env = ELECTRON_USE_VAAPI,1
env = ELECTRON_USE_WAYLAND,1
env = ELECTRON_USE_GL_DRIVER,egl
env = ELECTRON_DISABLE_GPU,0
env = ELECTRON_FORCE_GPU,1

# Дополнительные флаги через переменную
env = ELECTRON_EXTRA_FLAGS,--enable-features=VaapiVideoDecoder,UseOzonePlatform,WaylandWindowDecorations --disable-features=UseChromeOSDirectVideoDecoder --ozone-platform-hint=auto --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy

env = __GL_SYNC_TO_VBLANK,1
env = WLR_DRM_NO_ATOMIC,1
