# ===========================================
# Main hyprland config
# ===========================================

$config = $HOME/.config/hypr/config

source = $config/startup.conf
source = $config/appearance.conf
source = $config/keybinds.conf
source = $config/input.conf
source = $config/misc.conf

# ===========================================
# Core settings
# ===========================================
monitor = ,preferred,auto,1

env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,16

# GPU Settings
env = LIBVA_DRIVER_NAME,i965
env = LIBVA_DRIVERS_PATH,/usr/lib/dri
env = VDPAU_DRIVER,va_gl
env = WLR_NO_HARDWARE_CURSORS,1

# Qt/GTK
env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_LOGGING_RULES,qt.scenegraph.general=false
env = GTK_THEME,tokyonight-dark1
env = QT_QPA_PLATFORMTHEME,qt6ct

# Electron/Chromium
env = ELECTRON_USE_VAAPI,1
env = ELECTRON_USE_WAYLAND,1
env = ELECTRON_USE_GL_DRIVER,egl
env = ELECTRON_DISABLE_GPU,0
env = ELECTRON_FORCE_GPU,1


env = __GL_SYNC_TO_VBLANK,1
env = WLR_DRM_NO_ATOMIC,1
