# ===========================================
# Autostart
# ===========================================

# System services
exec-once = /usr/lib/hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY

# Hardware
exec-once = ~/bin/others/bt_autoconnect.sh                          # Auto-connect Bluetooth devices
exec-once = ~/bin/hypr/capslockd                                    # Capslock daemon (alternative: udev rules w/o keyd)
exec-once = ~/bin/hypr/hyprautokblayout                             # Auto kb layout switcher for nvim, vim, terminal etc


# Desktop environment
exec-once = waybar                                                  # Status bar
exec-once = sleep 2 && swaync                                       # Notification center
exec-once = swayosd-server -s ~/.config/swayosd/style.css           # OSD for volume/brightness/capslock
exec-once = hypridle                                                # Idle management
exec-once = ~/bin/others/swaybg-random                              # Random wallpaper on startup
exec-once = wl-paste --watch cliphist store                         # Clipboard history

# Apps and utilities
exec-once = ~/.config/rofi/nightshift/rofi-nightshift on            # Night shift effect
exec-once = python3 ~/.config/mpv/mpris-art-proxy.py                # MPRIS cover art proxy for mpv
exec-once = [ -f ~/.cache/hyprvisuals ] && ~/bin/hypr/hyprvisuals   # Hyprland visual effects toggle

# Disabled
# exec-once = ~/bin/others/                                         # Battery monitor

# Autostart apps on special workspaces
# exec-once = [workspace special:magic silent] zen-browser
