# ===========================================
# Автозапуск приложений
# ===========================================

exec-once = ~/bin/others/bt_autoconnect.sh
exec-once = ~/.config/rofi/nightshift/rofi-nightshift.sh
exec-once = ~/bin/others/random_wallpaper_wayland.sh
# exec-once = $HOME/.local/bin/battery_monitor.sh
exec-once = python3 ~/.config/mpv/mpris-art-proxy.py
exec-once = hypridle
exec-once = waybar
exec-once = sleep 2 && swaync
exec-once = swayosd-server -s ~/.config/swayosd/style.css
exec-once = wl-paste --watch cliphist store
exec-once = [ -f ~/.cache/hypr-perfmode ] && ~/bin/hypr/perfmode-toggle.sh
# exec-once = vicinae server
# exec-once = elephant

exec-once = /usr/lib/hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY

# Автозапуск на специальных рабочих пространствах
# exec-once = [workspace special:magic silent] zen-browser

